spring:
  application:
    name: product-stock-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
# Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
server:
  port: ${port:8800}
  